class CategoryItem {
  final String bookImagePath;
  final String bookName;
  final String bookWriterName;
  final int bookRatingNumber;
  final double bookPrice;

  CategoryItem({
    required this.bookImagePath,
    required this.bookName,
    required this.bookWriterName,
    required this.bookRatingNumber,
    required this.bookPrice,
  });
}

class CategoryShowBooks {
  final String categoryNameAppbarTitle;
  final List<CategoryItem> items;

  CategoryShowBooks({
    required this.categoryNameAppbarTitle,
    required this.items,
  });
}

List<CategoryShowBooks> categoryShowBooks = [
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Contemporary Stories',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Liberation War',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Essay',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Religious',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Literature',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Stories',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'History',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Horror Series',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Novel',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: "Children's Stories",
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Mystery',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Thriller',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Self-Development',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Science Fiction',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Politics',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'E-Book Exclusive',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Poetry',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Comics',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
  CategoryShowBooks(
    categoryNameAppbarTitle: 'Short Stories',
    items: [
      CategoryItem(
        bookImagePath: 'assets/images/book_7.png',
        bookName: 'Journey of life',
        bookWriterName: 'Al-hasan',
        bookRatingNumber: 30,
        bookPrice: 2,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_8.png',
        bookName: 'Before rain',
        bookWriterName: 'Ali kabir',
        bookRatingNumber: 20,
        bookPrice: 4,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_9.png',
        bookName: 'Lost love',
        bookWriterName: 'Hasan',
        bookRatingNumber: 10,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_10.png',
        bookName: 'The heart',
        bookWriterName: 'Mirza karim',
        bookRatingNumber: 40,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_11.png',
        bookName: 'Happiness',
        bookWriterName: 'William',
        bookRatingNumber: 45,
        bookPrice: 5,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_12.png',
        bookName: 'Losing',
        bookWriterName: 'Shakespeare',
        bookRatingNumber: 15,
        bookPrice: 8,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_13.png',
        bookName: 'Myself again',
        bookWriterName: 'Nobita',
        bookRatingNumber: 15,
        bookPrice: 10,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_14.png',
        bookName: 'Self love',
        bookWriterName: 'Ali mia',
        bookRatingNumber: 15,
        bookPrice: 6,
      ),
      CategoryItem(
        bookImagePath: 'assets/images/book_15.png',
        bookName: 'Beyond reach',
        bookWriterName: 'Najia',
        bookRatingNumber: 15,
        bookPrice: 3,
      ),
    ],
  ),
];
